import type { DEVICE_CATEGORIES, RECOVERY_KINDS, DEPENDENCY_KINDS, TRI_STATE, VISIBILITIES } from './constants';

export type Visibility = (typeof VISIBILITIES)[number];
export type DeviceCategory = (typeof DEVICE_CATEGORIES)[number];
export type RecoveryKind = (typeof RECOVERY_KINDS)[number];
export type DependencyKind = (typeof DEPENDENCY_KINDS)[number];
export type TriState = (typeof TRI_STATE)[number];

export interface Person {
  id: string;
  name: string;
  role: 'me' | 'partner' | 'parent' | 'child' | 'trusted-helper' | 'other';
  notes: string;
  visibility: Visibility;
}

export interface Device {
  id: string;
  label: string;
  role: string;
  category: DeviceCategory;
  ownerIds: string[];
  model: string;
  os: string;
  serialNumber: string;
  purchaseDate: string;
  location: string;
  encrypted: TriState;
  recoveryReferenceIds: string[];
  notes: string;
  visibility: Visibility;
  reviewDate: string;
}

export interface Account {
  id: string;
  label: string;
  provider: string;
  purpose: string;
  personIds: string[];
  mfa: TriState;
  recoveryReferenceIds: string[];
  notes: string;
  visibility: Visibility;
  reviewDate: string;
}

export interface Backup {
  id: string;
  label: string;
  destination: string;
  recoveryReferenceIds: string[];
  coversIds: string[];
  copies: 'one' | 'multiple' | 'unknown';
  lastCheckedDate: string;
  restoreTestedDate: string;
  restored: TriState;
  canRestorePersonIds: string[];
  notes: string;
  visibility: Visibility;
  reviewDate: string;
}

export interface RecoveryReference {
  id: string;
  label: string;
  kind: RecoveryKind;
  location: string;
  contactInfo: string;
  notes: string;
  visibility: Visibility;
}

export interface Dependency {
  id: string;
  sourceId: string;
  targetId: string;
  kind: DependencyKind;
  notes: string;
}

export interface ReviewItem {
  id: string;
  title: string;
  recurrenceDays: number | null;
  lastReviewedDate: string;
  nextReviewDate: string;
  status: 'ok' | 'due' | 'overdue' | 'snoozed';
  notes: string;
  linkedEntityIds: string[];
  /** source identifies whether the item was generated by the app or created manually. */
  source: 'app' | 'user';
}

export interface AppState {
  schemaVersion: number;
  people: Person[];
  devices: Device[];
  accounts: Account[];
  backups: Backup[];
  recoveryReferences: RecoveryReference[];
  dependencies: Dependency[];
  reviewItems: ReviewItem[];
  onboardingComplete: boolean;
  lastExportAt: string;
}

export interface AppBackup {
  schemaVersion: number;
  exportedAt: string;
  people: Person[];
  devices: Device[];
  accounts: Account[];
  backups: Backup[];
  recoveryReferences: RecoveryReference[];
  dependencies: Dependency[];
  reviewItems: ReviewItem[];
  onboardingComplete: boolean;
  lastExportAt: string;
}
